// ---------- game-data.json (generated by scripts/build-data.mjs) ----------

export type Refinement = 'Intact' | 'Exceptional' | 'Flawless' | 'Radiant';
export type Rarity = 'Common' | 'Uncommon' | 'Rare';

export interface RelicRef {
  relic: string; // "Axi A17"
  rarity: Rarity;
  chances: Partial<Record<Refinement, number>>;
  active: boolean; // farmable in current drop tables
}

export interface PrimeComponent {
  name: string; // "Systems"
  fullName: string; // "Wisp Prime Systems Blueprint"
  un?: string; // uniqueName, e.g. "/Lotus/Types/Recipes/WarframeRecipes/…"
  count: number;
  ducats?: number;
  market?: string; // warframe.market url slug
  relics: RelicRef[];
}

export interface Prime {
  name: string;
  un?: string;
  category: string;
  releaseDate?: string;
  image?: string;
  wikiaThumbnail?: string;
  founders?: true;
  farmable?: true;
  components: PrimeComponent[];
}

export interface RelicSource {
  where: string;
  mode?: string;
  rot?: string;
  stage?: string;
  chance: number;
}

/** Dependencia de crafteo entre dos ítems masterizables (Bolto ×2 → Akbolto). */
export interface BuildDep {
  name: string;
  count: number;
}

/** De dónde cae algo — misión, jefe, bounty — y con qué probabilidad. */
export interface Drop {
  where: string;
  chance: number;
}

/**
 * Pieza con nombre de un ítem no-prime: el blueprint, o Chassis, Barrel…
 * Se rastrea una a una desde el inventario, como las piezas prime; la clave
 * en `Progress.parts` la da `gearPartKey()`.
 */
export interface GearPart {
  name: string;
  un?: string;
  count: number;
  /** las mejores fuentes; sin esto la pieza se compra, se investiga o viene de una quest */
  drops?: Drop[];
}

/** Recurso que consume un crafteo: Alloy Plate ×1000, Forma ×1. */
export interface ResourceNeed {
  name: string;
  count: number;
}

export interface MasteryItem {
  name: string;
  un?: string;
  category: string;
  type?: string;
  isPrime?: true;
  cap: number;
  xp: number;
  /** total affinity at rank cap — threshold to detect "mastered" from XPInfo */
  aff?: number;
  founders?: true;
  /** ítems que consumen éste al craftearse — no venderlo mientras alguno siga pendiente */
  usedIn?: BuildDep[];
  /** ítems masterizables que se consumen al construir éste */
  needs?: BuildDep[];
  /** piezas con nombre (solo no-prime: las prime viven en `Prime.components`) */
  parts?: GearPart[];
  /** recursos que pide el crafteo, prime o no; solo interesan como déficit */
  resources?: ResourceNeed[];
  /** rango de maestría mínimo para usarlo */
  mr?: number;
  /** precio del ítem hecho en el mercado, en platino */
  plat?: number;
  /** lo que cuesta el blueprint en créditos — mercado o dojo, el catálogo no distingue */
  credits?: number;
  /** de dónde cae el ítem entero cuando no tiene blueprint (Kuva, Tenet…) */
  drops?: Drop[];
}

export interface GameData {
  builtAt: string;
  primes: Prime[];
  relicSources: Record<string, RelicSource[]>;
  masteryGear: MasteryItem[];
  /** star chart mission tags (SolNode… / SettlementNode…) */
  starChartNodes: string[];
  /** relic uniqueName (sin prefijo /Lotus/Types/Game/Projections/) -> "Lith S1 Intact" */
  relicIndex: Record<string, string>;
  /** nombre del recurso -> uniqueName, para leerlo del inventario importado */
  resourceIndex: Record<string, string>;
}

// ---------- user progress (localStorage) ----------

export type HistoryKind =
  | 'part'
  | 'built'
  | 'mastered'
  | 'unmastered'
  | 'extra'
  | 'import'
  | 'sync'
  | 'note'
  | 'target';

export interface HistoryEvent {
  t: string; // ISO date
  kind: HistoryKind;
  label: string;
  /** nombre del ítem al que se refiere, sin el prefijo del label */
  item?: string;
  xp?: number; // mastery XP delta, when applicable
}

export interface Extras {
  junctions: number; // completed junctions (x1000 XP)
  junctionsSP: number; // Steel Path junctions (x1000 XP)
  railjack: number; // intrinsic ranks (x1500 XP)
  drifter: number; // intrinsic ranks (x1500 XP)
  starChart: number; // XP directly (max ~27,519)
  starChartSP: number; // XP directly (max 27,519)
}

export interface Progress {
  v: 1;
  /** component fullName -> parts owned */
  parts: Record<string, number>;
  /** prime name -> built flag (crafted in foundry) */
  built: Record<string, boolean>;
  /** item name -> mastered (rank cap reached). Single source for primes + all gear */
  mastered: Record<string, boolean>;
  /**
   * item name -> rango actual (1..cap) de lo que aún no llega al tope.
   * El XP de maestría se gana por rango, no al llegar al cap: un arma en 15/30
   * ya dio la mitad. Sale del XPInfo del import; lo masterizado no entra aquí.
   */
  ranks: Record<string, number>;
  /** relic inventory: "Lith S1" -> counts per refinement (from AlecaFrame import) */
  relics: Record<string, Partial<Record<Refinement, number>>>;
  /**
   * nombre del ítem -> lo estás cazando ahora (sección 00 del panel). Primes
   * y equipo normal comparten el mapa: la mira vive en Primes y en Maestría.
   */
  targets: Record<string, boolean>;
  /**
   * recurso -> cantidad en el inventario, del último sync. Vacío hasta el
   * primer sync, y los lectores lo tratan como «no sé», no como «cero»:
   * inventar un déficit de Forma a quien no ha sincronizado sería mentir.
   */
  resources: Record<string, number>;
  extras: Extras;
  history: HistoryEvent[];
}

export const EMPTY_PROGRESS: Progress = {
  v: 1,
  parts: {},
  built: {},
  mastered: {},
  ranks: {},
  relics: {},
  targets: {},
  resources: {},
  extras: { junctions: 0, junctionsSP: 0, railjack: 0, drifter: 0, starChart: 0, starChartSP: 0 },
  history: [],
};
