// ---------- game-data.json (generated by scripts/build-data.mjs) ----------

export type Refinement = 'Intact' | 'Exceptional' | 'Flawless' | 'Radiant';
export type Rarity = 'Common' | 'Uncommon' | 'Rare';

export interface RelicRef {
  relic: string; // "Axi A17"
  rarity: Rarity;
  chances: Partial<Record<Refinement, number>>;
  active: boolean; // farmable in current drop tables
}

export interface PrimeComponent {
  name: string; // "Systems"
  fullName: string; // "Wisp Prime Systems Blueprint"
  un?: string; // uniqueName, e.g. "/Lotus/Types/Recipes/WarframeRecipes/…"
  count: number;
  ducats?: number;
  market?: string; // warframe.market url slug
  relics: RelicRef[];
}

export interface Prime {
  name: string;
  un?: string;
  category: string;
  releaseDate?: string;
  image?: string;
  wikiaThumbnail?: string;
  founders?: true;
  farmable?: true;
  components: PrimeComponent[];
}

export interface RelicSource {
  where: string;
  mode?: string;
  rot?: string;
  stage?: string;
  chance: number;
}

export interface MasteryItem {
  name: string;
  un?: string;
  category: string;
  type?: string;
  isPrime?: true;
  cap: number;
  xp: number;
  /** total affinity at rank cap — threshold to detect "mastered" from XPInfo */
  aff?: number;
  founders?: true;
}

export interface GameData {
  builtAt: string;
  primes: Prime[];
  relicSources: Record<string, RelicSource[]>;
  masteryGear: MasteryItem[];
  /** star chart mission tags (SolNode… / SettlementNode…) */
  starChartNodes: string[];
}

// ---------- user progress (localStorage) ----------

export type HistoryKind = 'part' | 'built' | 'mastered' | 'unmastered' | 'extra' | 'import' | 'note';

export interface HistoryEvent {
  t: string; // ISO date
  kind: HistoryKind;
  label: string;
  xp?: number; // mastery XP delta, when applicable
}

export interface Extras {
  junctions: number; // completed junctions (x1000 XP)
  junctionsSP: number; // Steel Path junctions (x1000 XP)
  railjack: number; // intrinsic ranks (x1500 XP)
  drifter: number; // intrinsic ranks (x1500 XP)
  starChart: number; // XP directly (max ~27,519)
  starChartSP: number; // XP directly (max 27,519)
}

export interface Progress {
  v: 1;
  /** component fullName -> parts owned */
  parts: Record<string, number>;
  /** prime name -> built flag (crafted in foundry) */
  built: Record<string, boolean>;
  /** item name -> mastered (rank cap reached). Single source for primes + all gear */
  mastered: Record<string, boolean>;
  extras: Extras;
  history: HistoryEvent[];
}

export const EMPTY_PROGRESS: Progress = {
  v: 1,
  parts: {},
  built: {},
  mastered: {},
  extras: { junctions: 0, junctionsSP: 0, railjack: 0, drifter: 0, starChart: 0, starChartSP: 0 },
  history: [],
};
